
NAME		:= ft_lex
MAKEFLAGS	+= --no-print-directory
 
CXX			:= c++
CXXFLAGS	:= -Wall -Wextra -Werror -std=c++17
 
CC			:= cc
CFLAGS		:= -Wall -Wextra
 
# --- Grammar used by scan/flex targets ---
GRAMMAR		?=
 
# --- Sources ---
SRCDIR		:= src/
FILES		:=	automata/Parser.cpp							\
				automata/Pipeline.cpp						\
				automata/SubsetConstruction.cpp				\
				automata/Thompson.cpp						\
				codegen/Codegen.cpp							\
				codegen/CodegenRust.cpp						\
				codegen/compression/DefaultChainBuilder.cpp	\
				codegen/compression/DenseRows.cpp			\
				codegen/compression/DiffProfileBuilder.cpp	\
				codegen/compression/TablePacker.cpp			\
				lexer_file/LexParser.cpp					\
				lexer_file/LineReader.cpp					\
				lexer_file/ParseError.cpp					\
				main.cpp
 
SRCS		:= $(addprefix $(SRCDIR), $(FILES))
 
OBJDIR		:= obj/
OBJS		:= $(patsubst $(SRCDIR)%.cpp,$(OBJDIR)%.o,$(SRCS))
 
# --- Template ---
TEMPLATE	:= src/template/yylex_template.c
TEMPLATE_H	:= src/codegen/yylex_template.h
 
# --- libl ---
LIBL_DIR	:= libl
LIBL		:= $(LIBL_DIR)/libl.a
 
# =============================================================================
# Pretty build: purple progress bar + banner
# =============================================================================
PURPLE		:= \033[35m
BOLD		:= \033[1m
DIM			:= \033[2m
RESET		:= \033[0m
 
BUILD_STEPS		:= $(OBJS) $(TEMPLATE_H) $(LIBL) $(NAME)
TOTAL_STEPS		:= $(words $(BUILD_STEPS))
PROGRESS_FILE	:= /tmp/.ft_lex_build_progress_$(shell id -u)
PROGRESS_LOCK	:= /tmp/.ft_lex_build_progress_$(shell id -u).lock
BAR_WIDTH		:= 20
 
# $(call step,Label shown next to the bar)
define step
	@flock $(PROGRESS_LOCK) -c ' \
		n=$$(cat $(PROGRESS_FILE) 2>/dev/null || echo 0); \
		n=$$((n+1)); \
		echo $$n > $(PROGRESS_FILE); \
		pct=$$(( n * 100 / $(TOTAL_STEPS) )); \
		[ $$pct -gt 100 ] && pct=100; \
		filled=$$(( pct * $(BAR_WIDTH) / 100 )); \
		empty=$$(( $(BAR_WIDTH) - filled )); \
		bar=""; [ $$filled -gt 0 ] && bar=$$(printf "%0.s#" $$(seq 1 $$filled)); \
		space=""; [ $$empty -gt 0 ] && space=$$(printf "%0.s-" $$(seq 1 $$empty)); \
		printf "\r\033[K$(PURPLE)$(BOLD)[%s%s] %3d%%$(RESET) $(DIM)%s$(RESET)" "$$bar" "$$space" "$$pct" "$(1)"; \
	'
endef
 

define banner
	@printf "\n"
	@printf "$(PURPLE)$(BOLD)"
	@printf "   __ _         _           \n"
	@printf "  / _| |       | |          \n"
	@printf " | |_| |_      | | _____  __\n"
	@printf " |  _| __|     | |/ _ \\ \\/ /\n"
	@printf " | | | |_______| |  __/>  < \n"
	@printf " |_|  \\__|_____|_|\\___/_/\\_\\ \n"
	@printf "$(RESET)$(DIM)            scanner generator - build OK$(RESET)\n\n"
endef


# Force the bar to 100% regardless of how many steps actually ran
# (some targets like $(LIBL) may be skipped entirely if already up to date).
define force_full_bar
	@bar=$$(printf "%0.s#" $$(seq 1 $(BAR_WIDTH))); \
	printf "\r\033[K$(PURPLE)$(BOLD)[%s] 100%%$(RESET) $(DIM)Done$(RESET)\n" "$$bar"
endef
 
# --- Rules ---
all: reset_progress $(TEMPLATE_H) $(LIBL) $(NAME)
	@n=$$(cat $(PROGRESS_FILE) 2>/dev/null || echo 0); \
	if [ "$$n" -eq 0 ]; then \
		printf "$(DIM)$(NAME) is already up to date.$(RESET)\n"; \
	else \
		$(MAKE) _show_success; \
	fi
 
_show_success:
	$(call force_full_bar)
	$(call banner)
 
reset_progress:
	@echo 0 > $(PROGRESS_FILE)
 
$(NAME): $(OBJS)
	@$(CXX) $(CXXFLAGS) -o $@ $^
	$(call step,Linking $(NAME))
 
$(LIBL):
	@$(MAKE) -C $(LIBL_DIR) >/dev/null
	$(call step,Building libl)
 
$(TEMPLATE_H): $(TEMPLATE)
	@mkdir -p $(dir $@)
	@if command -v xxd >/dev/null 2>&1; then \
		(cd $(dir $<) && xxd -i $(notdir $<)) > $@; \
	else \
		{ \
			echo "unsigned char yylex_template_c[] = {"; \
			od -An -v -t x1 $< | tr -s ' ' '\n' | grep -E '^[0-9a-f]{2}$$' | sed 's/^/0x/; s/$$/,/' | paste -sd' ' -; \
			echo "};"; \
			printf "unsigned int yylex_template_c_len = %s;\n" "$$(wc -c < $<)"; \
		} > $@; \
	fi
	$(call step,Embedding template)
 
obj/codegen/Codegen.o: src/codegen/Codegen.cpp $(TEMPLATE_H)
	@mkdir -p $(dir $@)
	@$(CXX) $(CXXFLAGS) -c -o $@ $<
	$(call step,Compiling $<)
 
$(OBJDIR)%.o: $(SRCDIR)%.cpp
	@mkdir -p $(dir $@)
	@$(CXX) $(CXXFLAGS) -c -o $@ $<
	$(call step,Compiling $<)
 
# --- scan: build lex.yy.c (generated by ft_lex) into a "scan" binary ---
scan: $(NAME) $(LIBL)
ifeq ($(strip $(GRAMMAR)),)
	$(error Usage: make scan GRAMMAR=path/to/file.l)
endif
	./$(NAME) $(GRAMMAR)
	$(CC) $(CFLAGS) -o scan lex.yy.c $(LIBL)
 
# --- flex: build lex.yy.c (generated by flex) into a "flex_scan" binary ---
# -lfl provides flex's default yywrap()/main(); not every system ships it,
# so fall back to linking without it if the grammar supplies its own.
flex: $(LIBL)
ifeq ($(strip $(GRAMMAR)),)
	$(error Usage: make flex GRAMMAR=path/to/file.l)
endif
	flex $(GRAMMAR)
	@$(CC) $(CFLAGS) -o flex_scan lex.yy.c -lfl 2>/dev/null || \
		$(CC) $(CFLAGS) -o flex_scan lex.yy.c
 
# --- tests: run every test script found in tests/ ---
TESTS_DIR	:= tests
 
tests:
	@for script in $(TESTS_DIR)/*.sh; do \
		echo "=== $$script ==="; \
		if [ -x "$$script" ]; then \
			"$$script" || exit 1; \
		else \
			bash "$$script" || exit 1; \
		fi; \
	done
 
clean:
	@rm -f $(OBJS) $(TEMPLATE_H) $(PROGRESS_FILE) $(PROGRESS_LOCK)
	@$(MAKE) -C $(LIBL_DIR) clean
	@printf "$(DIM)Cleaned object files for $(NAME)$(RESET)\n\n"; \
 
fclean: clean
	@rm -f $(NAME) scan flex_scan lex.yy.c
	@$(MAKE) -C $(LIBL_DIR) fclean
	@printf "$(DIM)Cleaned all artefacts for $(NAME)$(RESET)\n\n"; \
 
re: fclean all
 
.PHONY: all clean fclean re scan flex tests reset_progress _show_success
