#!/usr/bin/env bash

set -u

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEST_DIR="$ROOT_DIR/tests"
TMP_DIR="$ROOT_DIR/.tmp_compare_ft_lex_vs_flex"

PASS=0
FAIL=0
SKIP=0

print_usage() {
  echo "Usage: $0 [test_prefix ...]"
  echo "Examples:"
  echo "  $0            # run all tests found in tests/*.l"
  echo "  $0 06 07 08   # run only tests 06, 07 and 08"
}

note() {
  echo "[INFO] $*"
}

warn() {
  echo "[WARN] $*"
}

err() {
  echo "[ERR ] $*"
}

run_cmd() {
  "$@"
  return $?
}

build_tools() {
  note "Building ft_lex and libl..."
  if ! run_cmd make -C "$ROOT_DIR"; then
    err "Failed to build ft_lex"
    return 1
  fi
  if ! run_cmd make -C "$ROOT_DIR/libl"; then
    err "Failed to build libl"
    return 1
  fi
  return 0
}

collect_lex_files() {
  local selected=()
  local prefix

  if [[ "$#" -eq 0 ]]; then
    while IFS= read -r -d '' file; do
      selected+=("$file")
    done < <(find "$TEST_DIR" -maxdepth 1 -type f -name '*.l' -print0 | sort -z)
  else
    for prefix in "$@"; do
      local candidate
      candidate="$(find "$TEST_DIR" -maxdepth 1 -type f -name "${prefix}_*.l" | head -n 1)"
      if [[ -z "$candidate" ]]; then
        warn "No .l file found for prefix '$prefix'"
      else
        selected+=("$candidate")
      fi
    done
  fi

  if [[ "${#selected[@]}" -eq 0 ]]; then
    err "No lex test files found."
    return 1
  fi

  printf '%s\n' "${selected[@]}"
}

run_one_case() {
  local lex_file="$1"
  local base_name prefix input_file

  base_name="$(basename "$lex_file")"
  prefix="${base_name%%_*}"
  input_file="$TEST_DIR/${prefix}_input.txt"

  if [[ ! -f "$input_file" ]]; then
    warn "[$prefix] Missing input file: $input_file"
    SKIP=$((SKIP + 1))
    return 0
  fi

  local case_dir ft_c ft_bin ft_out flex_c flex_bin flex_out diff_file
  case_dir="$TMP_DIR/$prefix"
  mkdir -p "$case_dir"

  ft_c="$case_dir/ft_lex.yy.c"
  ft_bin="$case_dir/ft_scanner"
  ft_out="$case_dir/ft.out"

  flex_c="$case_dir/flex.yy.c"
  flex_bin="$case_dir/flex_scanner"
  flex_out="$case_dir/flex.out"

  diff_file="$case_dir/out.diff"

  echo
  note "[$prefix] Running with $(basename "$lex_file")"

  if ! run_cmd "$ROOT_DIR/ft_lex" "$lex_file" "$ft_c"; then
    err "[$prefix] ft_lex generation failed"
    FAIL=$((FAIL + 1))
    return 0
  fi

  if ! run_cmd gcc -Wall -Wextra -Werror "$ft_c" "$ROOT_DIR/libl/libl.a" -I "$ROOT_DIR/libl" -o "$ft_bin"; then
    err "[$prefix] Failed to compile scanner generated by ft_lex"
    FAIL=$((FAIL + 1))
    return 0
  fi

  if ! run_cmd "$ft_bin" "$input_file" > "$ft_out"; then
    err "[$prefix] ft_lex scanner execution failed"
    FAIL=$((FAIL + 1))
    return 0
  fi

  if ! run_cmd flex -o "$flex_c" "$lex_file"; then
    err "[$prefix] flex generation failed"
    FAIL=$((FAIL + 1))
    return 0
  fi

  if ! run_cmd gcc "$flex_c" "$ROOT_DIR/libl/src/main.c" "$ROOT_DIR/libl/src/yywrap.c" -I "$ROOT_DIR/libl" -o "$flex_bin"; then
    err "[$prefix] Failed to compile scanner generated by flex"
    FAIL=$((FAIL + 1))
    return 0
  fi

  if ! run_cmd "$flex_bin" "$input_file" > "$flex_out"; then
    err "[$prefix] flex scanner execution failed"
    FAIL=$((FAIL + 1))
    return 0
  fi

  if diff -u "$flex_out" "$ft_out" > "$diff_file"; then
    echo "[PASS] [$prefix] Output matches flex"
    PASS=$((PASS + 1))
  else
    echo "[FAIL] [$prefix] Output differs from flex"
    FAIL=$((FAIL + 1))
    echo "----- diff (flex vs ft_lex) -----"
    cat "$diff_file"
    echo "----------------------------------"
  fi

  return 0
}

main() {
  if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    print_usage
    exit 0
  fi

  if ! command -v flex >/dev/null 2>&1; then
    err "flex not found in PATH. Install flex first."
    exit 2
  fi

  mkdir -p "$TMP_DIR"

  if ! build_tools; then
    exit 1
  fi

  mapfile -t lex_files < <(collect_lex_files "$@")
  if [[ "${#lex_files[@]}" -eq 0 ]]; then
    err "No tests to run."
    exit 1
  fi

  local lex_file
  for lex_file in "${lex_files[@]}"; do
    run_one_case "$lex_file"
  done

  echo
  echo "========== Summary =========="
  echo "PASS: $PASS"
  echo "FAIL: $FAIL"
  echo "SKIP: $SKIP"
  echo "Artifacts: $TMP_DIR"
  echo "============================="

  if [[ "$FAIL" -gt 0 ]]; then
    exit 1
  fi
  exit 0
}

main "$@"
