/* -----------------------------------------------------------------------
 * Generated scanner runtime - do not edit by hand.
 * Produced by ft_lex. Template embedded via xxd -i at build time.
 * ----------------------------------------------------------------------- */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

@@PROLOGUE@@

@@COMPRESSION@@


/* -----------------------------------------------------------------------
 * yytext declaration - YYTEXT_MODE is replaced by the codegen:
 * - %pointer (default) -> "pointer"
 * - %array				-> "array"
 * ----------------------------------------------------------------------- */
#define @@YYTEXT_MODE@@
#if defined(YYARRAY_MODE)
#define YYLMAX			8192
	char	yytext[YYLMAX];
#else
	char	*yytext = NULL;
#endif

/* -----------------------------------------------------------------------
 * Accept-table entry: one per (rule, accepting state) pair.
 * trailing_len == -1 means no trailing context for this rule.
 * trailing_len == -2 means variable trailing context length.
 * ----------------------------------------------------------------------- */
typedef struct {
	int	rule_id;
	int	trailing_len;
	int trailing_dfa_id;
} YYAcceptEntry;

/* -----------------------------------------------------------------------
 * Tables generated by ft_lex - substituted at codegen time.
 *  yystart_states[]		- DFA entry states per condition (+ BOL variants)
 *  yytable[S][C]			- transition table; -1 on dead edge
 *  yyaccept_data[]			- flat array of (rule_id, trailing_len) pairs
 *  yyaccept_offset[S]		- index into yyaccept_data for state S (-1 if non-accepting)
 *  yyaccept_count[S]		- number of accepting rules at state S
 * ----------------------------------------------------------------------- */
@@TABLES@@

/* -----------------------------------------------------------------------
 * Public scanner state
 * ----------------------------------------------------------------------- */
int		yywrap(void);

int		yylineno	= 1;
size_t	yyleng		= 0;
FILE	*yyin		= NULL;
FILE	*yyout		= NULL;

/* -----------------------------------------------------------------------
 * Internal scanner state
 * ----------------------------------------------------------------------- */
static char		*yybuf				= NULL;
static size_t	yybuf_size			= 0;
static size_t	yybuf_capa			= 0;
static size_t	yybuf_pos			= 0;

static int		yycurrent_state		= 0;
static int		yymore_flag			= 0;
static size_t	yymore_len			= 0;

#define SINK	@@SINK@@

/* -----------------------------------------------------------------------
 * Candidate: one potential match collected during the scan phase.
 *  match_end		- absolute position in yybuf just past the full match
 * 					  (including trailing context if any)
 *  trailing_len	- chars to push back before invoking the action;
 * 					  -1 if rule has no trailing context
 * 					  -2 if tlen is not fixed.
 * ----------------------------------------------------------------------- */
typedef struct {
	int		rule_id;
	size_t	match_end;
	int		trailing_len;
	int		trailing_dfa_id;
} YYCandidate;


/* YYCAND_MAX caps the total (rule x length) pairs collected by token.
 * Override with -DYYCANDMAX=N if your grammar needs more. */
#ifndef YYCAND_MAX
#define YYCAND_MAX 15120
#endif

static YYCandidate	yycandidates[YYCAND_MAX];
static int			yyncandidates = 0;

#define YYBUF_INIT_SIZE	256


/* -----------------------------------------------------------------------
 * Public API macros
 * ----------------------------------------------------------------------- */

 /* Write the current token to yyout*/
#define ECHO fwrite(yytext, yyleng, 1, yyout)

/* Switch start condition. */
#define BEGIN yycurrent_state =

/* Rewind: keep only the first n bytes of the current match.
 * match_start is still the token's start at the time yyless runs. */
#define yyless(n) do {								\
	size_t	_yyless_n	= (size_t)(n);				\
	yybuf_pos			= base_start + _yyless_n;	\
	match_start			= yybuf_pos;				\
	yyleng				= _yyless_n;				\
	yytext[_yyless_n]	= '\0';						\
} while (0)

/* Append the next match to the current yytext instead of replacing it. */
#define yymore() (yymore_flag = 1)

/* -----------------------------------------------------------------------
 * yyread - serve the next byte from buffer from yyin, growing lazily.
 * Returns the next unsigned byte value, or EOF.
 * ----------------------------------------------------------------------- */
static int yyread(void)
{
	if (yybuf_pos < yybuf_size)
		return (unsigned char)yybuf[yybuf_pos++];

	int	c	= fgetc(yyin);
	if (c == EOF)
		return EOF;

	if (yybuf_size + 1 >= yybuf_capa) {
		size_t	new_capa	= yybuf_capa == 0 ? YYBUF_INIT_SIZE : yybuf_capa * 2;
		char	*tmp		= realloc(yybuf, new_capa);
		if (!tmp)
			return EOF;
		yybuf		= tmp;
		yybuf_capa	= new_capa;
	}

	yybuf[yybuf_size++]	= (char)c;
	yybuf[yybuf_size]	= '\0';
	yybuf_pos++;
	return (unsigned char)c;
}

/* -----------------------------------------------------------------------
 * input - read and consume the next raw character from yyin.
 * Tracks yylineno like the dispatch phase does for matched text.
 * ----------------------------------------------------------------------- */
int input(void)
{
	int c = yyread();

	if (c != EOF && c == '\n')
		yylineno++;

	return c;
}

/* -----------------------------------------------------------------------
 * unput - push a character back into the input stream so the next
 * input() (or scan) call rereads it.
 * 
 * If there's no room before yybuf_pos (buffer exhausted on the left),
 * grow the buffer and shift its content to make room, like
 * flex does, instead of silently dropping the character.
 * ----------------------------------------------------------------------- */
void unput(int c)
{
	if (yybuf_pos == 0) {
		size_t	new_capa	= yybuf_capa == 0 ? YYBUF_INIT_SIZE : yybuf_capa * 2;
		char	*tmp		= realloc(yybuf, new_capa);

		if (!tmp)
			return;

		memmove(tmp + (new_capa - yybuf_capa), tmp, yybuf_size + 1);
		yybuf_pos	= new_capa - yybuf_capa;
		yybuf_size	+= new_capa - yybuf_capa;
		yybuf		= tmp;
		yybuf_capa	= new_capa;
	}

	yybuf_pos--;
	yybuf[yybuf_pos] = (char)c;

	if (c == '\n' && yylineno > 1)
		yylineno--;
}

/* -----------------------------------------------------------------------
 * yy_assign_yytext - copy a slice of yybuf into yytext.
 * Handles both %pointer and %array modes, and yymore() accumulation.
 * ----------------------------------------------------------------------- */
static void yy_assign_yytext(size_t start, size_t len)
{
	size_t	total	= yymore_len + len;

#if defined(YYARRAY_MODE)
	if (total >= YYLMAX)
		total = YYLMAX - 1;
	memcpy(yytext + yymore_len, yybuf + start, total - yymore_len);
	yytext[total]	= '\0';
#else
	char	*buf	= malloc(total + 1);
	if (!buf)
		return;
	if (yymore_len > 0 && yytext)
		memcpy(buf, yytext, yymore_len);
	memcpy(buf + yymore_len, yybuf + start, len);
	buf[total]	= '\0';
	free(yytext);
	yytext	= buf;
#endif

	yyleng	= total;
}

/* -----------------------------------------------------------------------
 * yylex_destroy - free memory
 * ----------------------------------------------------------------------- */
void yylex_destroy(void)
{
	if (yybuf)
	{
		free(yybuf);
		yybuf		= NULL;
		yybuf_size	= 0;
		yybuf_capa	= 0;
		yybuf_pos	= 0;
	}
#if !defined(YYARRAY_MODE)
	if (yytext)
	{
		free(yytext);
		yytext	= NULL;
	}
#endif
}

#if defined(MODE_COMPRESSION)
/**
 * @brief Walk a state's default[] chain to resolve a compressed transition.
 *
 * Each state's row is split between its own next[]/check[] slots (the
 * symbols where it disagrees with its default[] parent) and whatever its
 * parent -- and the parent's parent, and so on -- already defines. A miss
 * at the current state (check[idx] != state) means "this state never
 * stored an exception for this symbol", not "no transition exists" -- so
 * we climb to default[state] and ask again there.
 *
 * default[] is built from a maximum spanning tree (see DefaultChainBuilder),
 * so the chain is acyclic by construction and always terminates: either
 * some state along the way owns the symbol, or we reach a root with
 * default[root] == -1 and return -1 (no transition / sink).
 *
 * @param state Starting state.
 * @param c     Input symbol (already cast to unsigned char by the caller).
 * @param base  Per-state offset into next[]/check[].
 * @param check Owner state of each next[] slot.
 * @param next  Transition destinations, compacted.
 * @param def   default[] chain: def[s] = parent of s, or -1 for a root.
 * @return Destination state, or -1 if no transition exists anywhere in the chain.
 */
static int yy_transition(int state, unsigned char c, int *base, int *check, int *next, int *def)
{
	int	s	= state;

	while (s != -1) {
		int	idx	= base[s] + c;

		if (check[idx] == s)
			return next[idx];
		s = def[s];
	}
	return -1;
}
#endif

/* -----------------------------------------------------------------------
 * yy_simulate_trailing - run an isolated trailing_context DFA over
 * yybuf[start..end) and return the length of the longest match.
 * 
 * Returns the committed length (chars belonging to the base pattern,
 * i.e. position of the longest trailing match minus start), or
 * (size_t)-1 if the trailing DFA never reached an accepting state. 
 * ----------------------------------------------------------------------- */
static size_t yy_simulate_trailing(int dfa_id, size_t start, size_t end)
{
	int		size	= yytrailing_sizes[dfa_id];
	int		*accept	= yytrailing_accepts[dfa_id];

#if !defined(MODE_COMPRESSION)
	int	(*table)[256]	= yytrailing_tables[dfa_id];
#else
	int	*base	= yytrailing_bases[dfa_id];
	int	*check	= yytrailing_checks[dfa_id];
	int	*next	= yytrailing_nexts[dfa_id];
	int	*def	= yytrailing_defaults[dfa_id];
#endif

	/* Try each split point left-to-right: leftmost match = longest base pattern. */
	for (size_t p = start; p <= end; p++) {
		int		state	= 0;
		size_t	pos		= p;

		while (pos < end) {
			unsigned char	c	= (unsigned char)yybuf[pos];

#if !defined(MODE_COMPRESSION)
			state	= table[state][c];
#else
			/* Same default[]-chain walk as the main scan loop below. */
			state	= yy_transition(state, c, base, check, next, def);
#endif
			if (state < 0)
				break;
			pos++;
		}

		if (pos == end && state >= 0 && state < size && accept[state])
			return p - start;
	}
	return (size_t)-1;
}

/* -----------------------------------------------------------------------
 * yylex - main scanner entry point.
 * ----------------------------------------------------------------------- */
int yylex(void)
{
	/* Verbatim code from indented lines in the rules section. */
	@@VERBATIM_RULES@@

	/* Persistent accross calls: start position of the next token in yybuf. */
	static size_t	match_start	= 0;

	static int	initialized	= 0;
	if (!initialized) {
		if (!yyin)	yyin	= stdin;
		if (!yyout)	yyout	= stdout;
		BEGIN(INITIAL);
		initialized	= 1;
	}

	/* reset yytext/yyleng unless yymore() was requested*/
	if (yymore_flag) {
		yymore_flag	= 0;
	} else {
#if !defined(YYARRAY_MODE)
		free(yytext);
		yytext	= NULL;
#endif
		yyleng		= 0;
		yymore_len	= 0;
	}

	/* ===================================================================
	 * Outer loop: scan and dispatch one token per iteration.
	 * =================================================================== */
	while (1) {
		int yy_at_bol	= (match_start == 0) || (yybuf[match_start - 1] == '\n');

		int state	= yy_at_bol
			? yystart_states[yycurrent_state + YYNB_CONDITIONS]
			: yystart_states[yycurrent_state];

		size_t base_start	= match_start;	
		yybuf_pos			= match_start;
		yyncandidates		= 0;

		/* -----------------------------------------------------------------
		 * SCAN PHASE — drive the DFA and collect all possible candidates.
		 *
		 * For each accepting state encountered, every rule is pushed onto
		 * the candidate array in REVERSE priority order (least-priority
		 * first). This means the highest-priority rule for the longest
		 * match ends up at the top (highest index), and the dispatch phase
		 * can simply iterate from top to bottom without sorting.
		 * ----------------------------------------------------------------- */
		while (1) {
			int	c	= yyread();

			if (c == EOF) {
				if (yyncandidates > 0)
					break;
				if (yywrap() == 1)
					return 0;
				continue;
			}

#if !defined(MODE_COMPRESSION)
			state	= yytable[state][(unsigned char)c];
#else
			/* Walk the default[] chain: climb to less-specific parent
			 * states until one of them explicitly owns this symbol.
			 * See yy_transition() above for the full explanation. */
			state	= yy_transition(state, (unsigned char)c, yybase, yycheck, yynext, yydefault);
#endif

			if (state == -1 || state == SINK)
				break;
				
			if (yyaccept_count[state] > 0) {
				int	base	= yyaccept_offset[state];
				int	cnt		= yyaccept_count[state];

				/* Push in reverse priority: index (cnt-1) first, 0 last.
				 * After the loop, index 0 (highest priority) is on top. */
				for (int ri = cnt - 1; ri >= 0 && yyncandidates < YYCAND_MAX; ri--) {
					yycandidates[yyncandidates].rule_id			= yyaccept_data[base + ri].rule_id;
					yycandidates[yyncandidates].match_end		= yybuf_pos;
					yycandidates[yyncandidates].trailing_len	= yyaccept_data[base + ri].trailing_len;
					yycandidates[yyncandidates].trailing_dfa_id = yyaccept_data[base + ri].trailing_dfa_id;
					yyncandidates++;
				}
			}
		}

		/* -----------------------------------------------------------------
		 * No candidate: POSIX default rule — echo the first unmatched char.
		 * ----------------------------------------------------------------- */
		if (yyncandidates == 0) {
			if (!feof(yyin))
				fputc(yybuf[match_start], yyout);
			match_start++;
			continue;
		}

		/* -----------------------------------------------------------------
		 * DISPATCH PHASE - try candidates from highest to lowest priority.
		 *
		 * Candidates are stored lowest-priority-first, so we iterate in
		 * reverse (from top index down to 0).
		 * 
		 * For each candidate:
		 * 	1. Compute committed_len (full match minus any trailing context).
		 * 	2. Assign yytext to the committed slice.
		 * 	3. Set yybuf_pos just past the committed part, effectively
		 * 	   pushing the trailing chars back into the input. Back up yylineno.
		 * 	4. Execute the rule action.
		 * 	   On REJECT: goto yy_try_next_candidate
		 * ----------------------------------------------------------------- */
		int	rule_executed	= 0;
		int ci				= yyncandidates - 1;

		for (; ci >= 0; ci--) {
			YYCandidate *cand	= &yycandidates[ci];

			size_t	full_len	= cand->match_end - base_start;
			size_t	committed_len;

			if (cand->trailing_len >= 0) {
				committed_len = full_len - (size_t)cand->trailing_len;
			} else if (cand->trailing_len == -2) {
				committed_len = yy_simulate_trailing(cand->trailing_dfa_id, match_start, cand->match_end);
				if (committed_len == (size_t)-1)
					continue;
			} else {
				committed_len = full_len;
			}

			yy_assign_yytext(base_start, committed_len);
			yybuf_pos	= base_start + committed_len;

			int saved_yylineno	= yylineno;
			for (size_t i = yymore_len; i < yyleng; i++) {
				if (yytext[i] == '\n')
					yylineno++;
			}

			match_start = yybuf_pos;

			#define REJECT goto yy_try_next_candidate

			switch (cand->rule_id) {
@@RULES@@
			}

			#undef REJECT

			rule_executed = 1;
			break;

yy_try_next_candidate:
			match_start	= base_start;
			yylineno	= saved_yylineno;
		}

		/* All candidates rejected or none succeeded: echo first char. */
		if (!rule_executed) {
			if (!feof(yyin))
				fputc(yybuf[match_start], yyout);
			match_start++;
			continue;
		}

		/* Handle yymore(), bookkeeping, or release yytext. */
		if (yymore_flag) {
			yymore_len = yyleng;
		} else {
#if !defined(YYARRAY_MODE)
			free(yytext);
			yytext = NULL;
#endif
			yyleng		= 0;
			yymore_len	= 0;
		}
		yymore_flag = 0;
	}
}

@@EPILOGUE@@